### ISSUE TITLE
Issue with analyze_logs.py

### ISSUE THREAD

**Issue by everettperiman** [Pemigrade/minecraft-server-hosts#3]
I get the error below when I am analyzing my logs from a recent run. I am running Lubuntu 20.04 fully updated, and am using the logs from a 2 hour long session. The log is featured in my fork of this project.
"Traceback (most recent call last):
  File "analyze_logs.py", line 65, in <module>
    median_mspt_dist = statistics.NormalDist.from_samples(median_mspt_list)
  File "/usr/lib/python3.8/statistics.py", line 921, in from_samples
    xbar = fmean(data)
  File "/usr/lib/python3.8/statistics.py", line 345, in fmean
    raise StatisticsError('fmean requires at least one data point') from None
statistics.StatisticsError: fmean requires at least one data point
"

**Comment by everettperiman** [comment]
Seems to be an error with Linux based systems. When the same logs are used under Windows it seems to work just fine.
